name: 'm-g-r'
description: 'create release'
inputs:
  github-token:
    description: 'github-token'
    required: true
  directory:
    description: 'directory containing artifacts'
    required: true
  tag-prefix:
    description: 'tag name prefix'
    required: true
    default: 'refs/tags/v'
  bump-up-branch-prefix:
    description: 'bump up branch name prefix'
    required: true
    default: 'bump-version-'
runs:
  using: 'node12'
  main: 'dist/index.js'
